# alias exemacs="tlbx enter exercismbox emacs"
alias flatmacs="FLATPAK_ENABLE_SDK_EXT=ziglang,openjdk11,texlive,rust-stable,golang,haskell,php74,ldc,dmd,node14,llvm12 flatpak run org.gnu.emacs"
alias shbrowsybox="tlbx enter -it browsybox bash"
alias rshbrowsybox="tlbx enter -it --user=root browsybox bash"
alias shactibox="tlbx enter -it actibox bash"
alias rshactibox="tlbx enter -it --user=root actibox bash"
alias shexercismbox="tlbx enter -it exercismbox bash"
alias rshexercismbox="tlbx enter -it --user=root exercismbox bash"
alias browsybrave="tlbx enter browsybox brave-browser"
alias browsyfox="tlbx enter browsybox firefox"
alias pbrowsybrave="tlbx enter browsybox brave-browser --incognito"
alias pbrowsyfox="tlbx enter browsybox firefox --private-window"
alias actifox="tlbx enter actibox firefox"
alias pactifox="tlbx enter actibox firefox --private-window"
